#!/bin/sh
### BEGIN INIT INFO
# Provides:          openplc
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Prepares and starts openplc
# Description:       Prepares and starts openplc
### END INIT INFO

NAME="webserver.py"
WORKDIR=/opt/OpenPLC_v3/webserver/
DAEMON=/usr/bin/python3
LOGFILE=/tmp/openplc.log
PIDFILE=/tmp/openplc.pid

do_start () {
	cd $WORKDIR
	export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
        echo "start openplc"
	echo "path: $PATH" > $LOGFILE
	$DAEMON ./$NAME >>$LOGFILE 2>&1 &
}

do_stop () {
    kill -15 $Pid
}

if [ -f $PIDFILE ]
then
	Pid=`cat $PIDFILE`
fi

case "$1" in
'start')
		if [ -f $PIDFILE ] ; then
				if pidof $DAEMON > 1; then
						echo "Not starting $NAME - instance already running with PID: $Pid"
				else
						echo "Starting $NAME"
						do_start
						echo $! > $PIDFILE
				fi
		else
				echo "Starting $NAME"
				do_start
				echo $! > $PIDFILE
		fi
		;;

'stop')
		if [ -f $PIDFILE ] ; then
				echo "stopping $NAME"
				do_stop
		else
				echo "Cannot stop $NAME - no Pidfile found!"
		fi
		;;

'restart')
		$0 stop
		sleep 2s
		$0 start
		;;

'status')
		if [ -f $PIDFILE ] ; then
				if pidof $DAEMON > 1; then
						echo "$NAME running with PID: [$Pid]"						
				else
						echo "$NAME not running"
				fi
		else
				echo "$PIDFILE does not exist! Cannot process $NAME status!"
				exit 1
		fi
		;;

*)
		echo "usage: $0 { start | stop | restart | status }"
		;;

esac
exit 0

