name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install script
      run: bash install.sh linux
    - name: compile blank_program
      run: |
        cd webserver
        bash scripts/change_hardware_layer.sh blank_linux
        bash scripts/compile_program.sh blank_program.st
